### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by marcusjwhelan** [timbarclay/ts-react-electron-demo#1]
### First 
    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "dist" is not an absolute path!

* Fixed by adding - path.join(__dirname, "dist") in webpack.config.js

### Second
    ERROR in ./src/renderer/renderer.tsx
    (14,20): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/username/ts-react-electron-demo/node_modules/@types/r...' has no compatible call signatures.

* This one I did not figure out. Do you plan on having a hot reload development environment?
    - if so [example-project](https://github.com/iRath96/electron-react-typescript-boilerplate) would be a good start. 

I am currently using the example-projects's format but would rather have my items split like yours but cannot figure out the testing. If I do I will surely make an example repo. There doesn't seem to be any good React+TypeScript+Webpack+Electron project boilerplates that were built for both development and production.

**Comment by timbarclay** [comment]
Thanks for raising the issue. That second problem seems to have been an issue with the type definition for redux-logger not being correct. I updated the versions of redux, redux-logger and the redux-logger types and now everything should be working.
